language: python

python:
- '3.6'

before_install:
- sudo apt update
- sudo apt install -y cargo

install:
- pip install -r requirements.txt

script:
  - pytest ./pibakesoftware/test/test.py

deploy:
  provider: pypi
  username: "wymiller"
  password:
    secure: "DS8MwXdK4E4UoiwVUdZ7UIr/HjsLE+sJWn5Uh97IPq4fWw7O9Q1VNBoSYuMbTV2g4QbT3gzsiQ31eBV//SUGJJyWHDfeq7Bd9N19uX8VGnkaynk/R9qR5UsQmNGywtsrKxt2UrspUx7GS2j5mdfsJZzVqhSkO87rvr5eoMEU1BZ9k69SPRa6Ghb1yKXMEjPKfHjUTjdefjVX3GwkD2G9xCD7Be8zUEGScRbpIsnTmHaxGgqPPUTfxqHLhwlKeq53cucjMYG3GV1vZdooM8WzoZ7sHoDkipWze/hFg5qjQj0zNmahI4wDMtQsORg/zlTD+leJPfWE74I4HE7cDhQtVW208+usVRS15BnoDAYhDQHJXTofTf4aJKBRVvzBANVqOOyIfO5q8RQ2K2kS/XnRd6ea/Mr7aH/VOca/iDFkKkJQhTouotYJaqYkRhfQWlH0l3qlWLAW2/WfAwlgL+Jn1ZA9PyfV9bC/Afj68gElos0ArDUtluBk6x/NaPj1LCRW4fqhmfopylbP0w3V+unUKdsO+eHC/5uEvfH4a6GZelTtJwUYh1L4dbY0N0TyGFZyYMSW1tqQETybm3TmbizM82D6iy9F2NXy0HMzn4fLjPbJBsNQ9lmx6htGXzILZv+HQu/GTmmUeJIkVsmogTYnTbS3Rxfq3lXCw1hPr81etvk="