language: python

python:
- '3.6'

before_install:
- sudo apt update
- sudo apt install -y cargo

install:
- pip install -r requirements.txt

script:
  - pytest ./pibakesoftware/test/test.py

deploy:
  provider: pypi
  username: "wymiller"
  password:
    secret: "ZkTkTCndjsS0RnxnnWvdpOCLzwgK472q+kxYNSBehXZONxyFu6ePRd9wqgPgOSN+aB9XjLuAhvduyfaiTd68RGK3NI5G0uSMKKYdEYvd3sBPNmjVLhKp0CURFydTqUdZMdk2BqGLOCqLS+C3lzUk0ja/8gQnI/PDvczojATV+e2BERO+Ym2B4Y2YQ2D21pZCM5QKXpnxtW3YSwCYJp4zXX91XixidvSYitHdXouBtRfiN3rLSnl0JkYtTR6o1gJzBwjlE8c8d1xrhpLIbOCCRvaO+GSe8nmGt+xymhx8rLl/jFsqJUZDbxmD/Vl39Ngz9OPxVlfK1MfFRzZnguHeAfZN5OyQx9H4FGQq0xzifVLjjYqgAPvybgxA/jtPOpsaXCJbo7wqZN/J6WC4Gms9sY6dvM/ru99w1AcpCIdTLMHj2lBZ2zac114Zgd7HAjnkqjDKUqyRv7haVoCR+2+QU1oBx7l3EwXsrALwHiQzQxmXNdsbtf5GPN3fYX61/FTrMUSmGtT2B96eJwirHi4bYFeoaY+eW+VljDQtNYYMU6o2sc/22wJDtYhzsLb238zQvR8pPLyD3p+VolMqJsnzl6cn0Yy89CzfeM/WCC9gorfAWttP+kHBghMqIWFOJO6WmR9MyWSfGihaA/GxxWX0w5m3g8Lv8AeJh+zN4qpC6wc="
  server: https://test.pypi.org/legacy/
